/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SituacionesIndexRouteImport } from './routes/situaciones.index'
import { Route as SituacionesIdRouteImport } from './routes/situaciones.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituacionesIndexRoute = SituacionesIndexRouteImport.update({
  id: '/situaciones/',
  path: '/situaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituacionesIdRoute = SituacionesIdRouteImport.update({
  id: '/situaciones/$id',
  path: '/situaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones/': typeof SituacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones': typeof SituacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones/': typeof SituacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/situaciones/$id' | '/situaciones/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/situaciones/$id' | '/situaciones'
  id: '__root__' | '/' | '/situaciones/$id' | '/situaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SituacionesIdRoute: typeof SituacionesIdRoute
  SituacionesIndexRoute: typeof SituacionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situaciones/': {
      id: '/situaciones/'
      path: '/situaciones'
      fullPath: '/situaciones/'
      preLoaderRoute: typeof SituacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situaciones/$id': {
      id: '/situaciones/$id'
      path: '/situaciones/$id'
      fullPath: '/situaciones/$id'
      preLoaderRoute: typeof SituacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SituacionesIdRoute: SituacionesIdRoute,
  SituacionesIndexRoute: SituacionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
