/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalizarRouteImport } from './routes/analizar'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as GlosarioRouteImport } from './routes/glosario'
import { Route as GuionesRouteImport } from './routes/guiones'
import { Route as LimitesYSeguridadRouteImport } from './routes/limites-y-seguridad'
import { Route as MiEspacioRouteImport } from './routes/mi-espacio'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RegulacionRouteImport } from './routes/regulacion'
import { Route as RelacionesRouteImport } from './routes/relaciones'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as SobreElProyectoRouteImport } from './routes/sobre-el-proyecto'
import { Route as TdahAdhdRouteImport } from './routes/tdah-adhd'
import { Route as SituacionesIndexRouteImport } from './routes/situaciones.index'
import { Route as SituacionesIdRouteImport } from './routes/situaciones.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalizarRoute = AnalizarRouteImport.update({
  id: '/analizar',
  path: '/analizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosarioRoute = GlosarioRouteImport.update({
  id: '/glosario',
  path: '/glosario',
  getParentRoute: () => rootRouteImport,
} as any)
const GuionesRoute = GuionesRouteImport.update({
  id: '/guiones',
  path: '/guiones',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitesYSeguridadRoute = LimitesYSeguridadRouteImport.update({
  id: '/limites-y-seguridad',
  path: '/limites-y-seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const MiEspacioRoute = MiEspacioRouteImport.update({
  id: '/mi-espacio',
  path: '/mi-espacio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulacionRoute = RegulacionRouteImport.update({
  id: '/regulacion',
  path: '/regulacion',
  getParentRoute: () => rootRouteImport,
} as any)
const RelacionesRoute = RelacionesRouteImport.update({
  id: '/relaciones',
  path: '/relaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreElProyectoRoute = SobreElProyectoRouteImport.update({
  id: '/sobre-el-proyecto',
  path: '/sobre-el-proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const TdahAdhdRoute = TdahAdhdRouteImport.update({
  id: '/tdah-adhd',
  path: '/tdah-adhd',
  getParentRoute: () => rootRouteImport,
} as any)
const SituacionesIndexRoute = SituacionesIndexRouteImport.update({
  id: '/situaciones/',
  path: '/situaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituacionesIdRoute = SituacionesIdRouteImport.update({
  id: '/situaciones/$id',
  path: '/situaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analizar': typeof AnalizarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/glosario': typeof GlosarioRoute
  '/guiones': typeof GuionesRoute
  '/limites-y-seguridad': typeof LimitesYSeguridadRoute
  '/mi-espacio': typeof MiEspacioRoute
  '/privacidad': typeof PrivacidadRoute
  '/regulacion': typeof RegulacionRoute
  '/relaciones': typeof RelacionesRoute
  '/simulador': typeof SimuladorRoute
  '/sobre-el-proyecto': typeof SobreElProyectoRoute
  '/tdah-adhd': typeof TdahAdhdRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones/': typeof SituacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analizar': typeof AnalizarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/glosario': typeof GlosarioRoute
  '/guiones': typeof GuionesRoute
  '/limites-y-seguridad': typeof LimitesYSeguridadRoute
  '/mi-espacio': typeof MiEspacioRoute
  '/privacidad': typeof PrivacidadRoute
  '/regulacion': typeof RegulacionRoute
  '/relaciones': typeof RelacionesRoute
  '/simulador': typeof SimuladorRoute
  '/sobre-el-proyecto': typeof SobreElProyectoRoute
  '/tdah-adhd': typeof TdahAdhdRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones': typeof SituacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analizar': typeof AnalizarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/glosario': typeof GlosarioRoute
  '/guiones': typeof GuionesRoute
  '/limites-y-seguridad': typeof LimitesYSeguridadRoute
  '/mi-espacio': typeof MiEspacioRoute
  '/privacidad': typeof PrivacidadRoute
  '/regulacion': typeof RegulacionRoute
  '/relaciones': typeof RelacionesRoute
  '/simulador': typeof SimuladorRoute
  '/sobre-el-proyecto': typeof SobreElProyectoRoute
  '/tdah-adhd': typeof TdahAdhdRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones/': typeof SituacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analizar'
    | '/como-funciona'
    | '/contacto'
    | '/glosario'
    | '/guiones'
    | '/limites-y-seguridad'
    | '/mi-espacio'
    | '/privacidad'
    | '/regulacion'
    | '/relaciones'
    | '/simulador'
    | '/sobre-el-proyecto'
    | '/tdah-adhd'
    | '/situaciones/$id'
    | '/situaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analizar'
    | '/como-funciona'
    | '/contacto'
    | '/glosario'
    | '/guiones'
    | '/limites-y-seguridad'
    | '/mi-espacio'
    | '/privacidad'
    | '/regulacion'
    | '/relaciones'
    | '/simulador'
    | '/sobre-el-proyecto'
    | '/tdah-adhd'
    | '/situaciones/$id'
    | '/situaciones'
  id:
    | '__root__'
    | '/'
    | '/analizar'
    | '/como-funciona'
    | '/contacto'
    | '/glosario'
    | '/guiones'
    | '/limites-y-seguridad'
    | '/mi-espacio'
    | '/privacidad'
    | '/regulacion'
    | '/relaciones'
    | '/simulador'
    | '/sobre-el-proyecto'
    | '/tdah-adhd'
    | '/situaciones/$id'
    | '/situaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalizarRoute: typeof AnalizarRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  GlosarioRoute: typeof GlosarioRoute
  GuionesRoute: typeof GuionesRoute
  LimitesYSeguridadRoute: typeof LimitesYSeguridadRoute
  MiEspacioRoute: typeof MiEspacioRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RegulacionRoute: typeof RegulacionRoute
  RelacionesRoute: typeof RelacionesRoute
  SimuladorRoute: typeof SimuladorRoute
  SobreElProyectoRoute: typeof SobreElProyectoRoute
  TdahAdhdRoute: typeof TdahAdhdRoute
  SituacionesIdRoute: typeof SituacionesIdRoute
  SituacionesIndexRoute: typeof SituacionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analizar': {
      id: '/analizar'
      path: '/analizar'
      fullPath: '/analizar'
      preLoaderRoute: typeof AnalizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosario': {
      id: '/glosario'
      path: '/glosario'
      fullPath: '/glosario'
      preLoaderRoute: typeof GlosarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guiones': {
      id: '/guiones'
      path: '/guiones'
      fullPath: '/guiones'
      preLoaderRoute: typeof GuionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limites-y-seguridad': {
      id: '/limites-y-seguridad'
      path: '/limites-y-seguridad'
      fullPath: '/limites-y-seguridad'
      preLoaderRoute: typeof LimitesYSeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-espacio': {
      id: '/mi-espacio'
      path: '/mi-espacio'
      fullPath: '/mi-espacio'
      preLoaderRoute: typeof MiEspacioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulacion': {
      id: '/regulacion'
      path: '/regulacion'
      fullPath: '/regulacion'
      preLoaderRoute: typeof RegulacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relaciones': {
      id: '/relaciones'
      path: '/relaciones'
      fullPath: '/relaciones'
      preLoaderRoute: typeof RelacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-el-proyecto': {
      id: '/sobre-el-proyecto'
      path: '/sobre-el-proyecto'
      fullPath: '/sobre-el-proyecto'
      preLoaderRoute: typeof SobreElProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tdah-adhd': {
      id: '/tdah-adhd'
      path: '/tdah-adhd'
      fullPath: '/tdah-adhd'
      preLoaderRoute: typeof TdahAdhdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situaciones/': {
      id: '/situaciones/'
      path: '/situaciones'
      fullPath: '/situaciones/'
      preLoaderRoute: typeof SituacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situaciones/$id': {
      id: '/situaciones/$id'
      path: '/situaciones/$id'
      fullPath: '/situaciones/$id'
      preLoaderRoute: typeof SituacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalizarRoute: AnalizarRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  GlosarioRoute: GlosarioRoute,
  GuionesRoute: GuionesRoute,
  LimitesYSeguridadRoute: LimitesYSeguridadRoute,
  MiEspacioRoute: MiEspacioRoute,
  PrivacidadRoute: PrivacidadRoute,
  RegulacionRoute: RegulacionRoute,
  RelacionesRoute: RelacionesRoute,
  SimuladorRoute: SimuladorRoute,
  SobreElProyectoRoute: SobreElProyectoRoute,
  TdahAdhdRoute: TdahAdhdRoute,
  SituacionesIdRoute: SituacionesIdRoute,
  SituacionesIndexRoute: SituacionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
