/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as GlosarioRouteImport } from './routes/glosario'
import { Route as GuionesRouteImport } from './routes/guiones'
import { Route as LimitesYSeguridadRouteImport } from './routes/limites-y-seguridad'
import { Route as RegulacionRouteImport } from './routes/regulacion'
import { Route as RelacionesRouteImport } from './routes/relaciones'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as SituacionesIndexRouteImport } from './routes/situaciones.index'
import { Route as SituacionesIdRouteImport } from './routes/situaciones.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosarioRoute = GlosarioRouteImport.update({
  id: '/glosario',
  path: '/glosario',
  getParentRoute: () => rootRouteImport,
} as any)
const GuionesRoute = GuionesRouteImport.update({
  id: '/guiones',
  path: '/guiones',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitesYSeguridadRoute = LimitesYSeguridadRouteImport.update({
  id: '/limites-y-seguridad',
  path: '/limites-y-seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulacionRoute = RegulacionRouteImport.update({
  id: '/regulacion',
  path: '/regulacion',
  getParentRoute: () => rootRouteImport,
} as any)
const RelacionesRoute = RelacionesRouteImport.update({
  id: '/relaciones',
  path: '/relaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const SituacionesIndexRoute = SituacionesIndexRouteImport.update({
  id: '/situaciones/',
  path: '/situaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituacionesIdRoute = SituacionesIdRouteImport.update({
  id: '/situaciones/$id',
  path: '/situaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/glosario': typeof GlosarioRoute
  '/guiones': typeof GuionesRoute
  '/limites-y-seguridad': typeof LimitesYSeguridadRoute
  '/regulacion': typeof RegulacionRoute
  '/relaciones': typeof RelacionesRoute
  '/simulador': typeof SimuladorRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones/': typeof SituacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/glosario': typeof GlosarioRoute
  '/guiones': typeof GuionesRoute
  '/limites-y-seguridad': typeof LimitesYSeguridadRoute
  '/regulacion': typeof RegulacionRoute
  '/relaciones': typeof RelacionesRoute
  '/simulador': typeof SimuladorRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones': typeof SituacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/glosario': typeof GlosarioRoute
  '/guiones': typeof GuionesRoute
  '/limites-y-seguridad': typeof LimitesYSeguridadRoute
  '/regulacion': typeof RegulacionRoute
  '/relaciones': typeof RelacionesRoute
  '/simulador': typeof SimuladorRoute
  '/situaciones/$id': typeof SituacionesIdRoute
  '/situaciones/': typeof SituacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/glosario'
    | '/guiones'
    | '/limites-y-seguridad'
    | '/regulacion'
    | '/relaciones'
    | '/simulador'
    | '/situaciones/$id'
    | '/situaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/glosario'
    | '/guiones'
    | '/limites-y-seguridad'
    | '/regulacion'
    | '/relaciones'
    | '/simulador'
    | '/situaciones/$id'
    | '/situaciones'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/glosario'
    | '/guiones'
    | '/limites-y-seguridad'
    | '/regulacion'
    | '/relaciones'
    | '/simulador'
    | '/situaciones/$id'
    | '/situaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  GlosarioRoute: typeof GlosarioRoute
  GuionesRoute: typeof GuionesRoute
  LimitesYSeguridadRoute: typeof LimitesYSeguridadRoute
  RegulacionRoute: typeof RegulacionRoute
  RelacionesRoute: typeof RelacionesRoute
  SimuladorRoute: typeof SimuladorRoute
  SituacionesIdRoute: typeof SituacionesIdRoute
  SituacionesIndexRoute: typeof SituacionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosario': {
      id: '/glosario'
      path: '/glosario'
      fullPath: '/glosario'
      preLoaderRoute: typeof GlosarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guiones': {
      id: '/guiones'
      path: '/guiones'
      fullPath: '/guiones'
      preLoaderRoute: typeof GuionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limites-y-seguridad': {
      id: '/limites-y-seguridad'
      path: '/limites-y-seguridad'
      fullPath: '/limites-y-seguridad'
      preLoaderRoute: typeof LimitesYSeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulacion': {
      id: '/regulacion'
      path: '/regulacion'
      fullPath: '/regulacion'
      preLoaderRoute: typeof RegulacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relaciones': {
      id: '/relaciones'
      path: '/relaciones'
      fullPath: '/relaciones'
      preLoaderRoute: typeof RelacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situaciones/': {
      id: '/situaciones/'
      path: '/situaciones'
      fullPath: '/situaciones/'
      preLoaderRoute: typeof SituacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situaciones/$id': {
      id: '/situaciones/$id'
      path: '/situaciones/$id'
      fullPath: '/situaciones/$id'
      preLoaderRoute: typeof SituacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  GlosarioRoute: GlosarioRoute,
  GuionesRoute: GuionesRoute,
  LimitesYSeguridadRoute: LimitesYSeguridadRoute,
  RegulacionRoute: RegulacionRoute,
  RelacionesRoute: RelacionesRoute,
  SimuladorRoute: SimuladorRoute,
  SituacionesIdRoute: SituacionesIdRoute,
  SituacionesIndexRoute: SituacionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
